version: "3.8"
services:
  app:
    image: "${IMAGE_REPO}:${IMAGE_TAG}"   # filled by ApplicationStart.ps1
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/petclinic?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "petclinic"
      SPRING_DATASOURCE_PASSWORD: "petclinic"
    ports:
      # Host 8086 -> container 8085  (Tomcat logs show 8085 inside)
      - "${SERVER_PORT:-8086}:8085"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
