services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: "spring-petclinic:prod-current"   # pinned to exact tag at runtime by ApplicationStart.ps1
    depends_on:
      db: { condition: service_healthy }
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "petclinic"
      SPRING_SQL_INIT_MODE: "always"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      SERVER_PORT: "8080"
    ports:
      - "8086:8080"
    restart: unless-stopped

volumes:
  mysql-data-prod:
