# octopus/docker-compose.prod.yml
# Octopus substitutes ImageTag and ServerPort OR our Deploy.ps1 will force them.

services:
  db:
    image: mysql:8.0
    volumes:
      - octopus_mysql-data-staging:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: "spring-petclinic:#{ImageTag}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Spring Boot reads uppercase underscore envs:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "petclinic"
      SPRING_SQL_INIT_MODE: "always"   # ensure schema/data init when profile=mysql
      SERVER_PORT: "8080"              # container internal port
    ports:
      - "#{ServerPort}:8080"           # host:container (Production should be 8086)
    restart: unless-stopped

volumes:
  octopus_mysql-data-staging:
