# octopus/docker-compose.prod.yml
# Octopus will substitute #{ImageTag} and #{ServerPort}. Our Deploy.ps1 also forces them at runtime.

services:
  db:
    image: mysql:8.0
    volumes:
      - octopus_mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: "spring-petclinic:#{ImageTag}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "petclinic"
      SPRING_SQL_INIT_MODE: "always"
      SERVER_PORT: "8080"           # container port
    ports:
      - "#{ServerPort}:8080"        # host:container (Production = 8086:8080)
    restart: unless-stopped

volumes:
  octopus_mysql-data:
