# docker-compose.staging.yml (for Jenkins staging on port 8085)
# Compose v2; uses COMPOSE_PROJECT_NAME=petclinic-ci from Jenkins env

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    volumes:
      - mysql-data-staging:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: "spring-petclinic:staging"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      spring.datasource.url: "jdbc:mysql://db:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      spring.datasource.username: "root"
      spring.datasource.password: "petclinic"
      SERVER_PORT: "8080"
    ports:
      - "8085:8080"
    restart: unless-stopped

volumes:
  mysql-data-staging:
