services:
  db:
    image: mysql:8.0
    #container_name: petclinic-db
    environment:
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: "spring-petclinic:#{ImageTag}"     # Octopus substitutes this
    #container_name: petclinic-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://petclinic-db:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "petclinic"
      SERVER_PORT: "8080"
    ports:
      - "#{ServerPort}:8080"
    restart: unless-stopped

volumes:
  mysql-data:
