route:
  receiver: 'slack'
  group_by: ['alertname','instance']
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 2h

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        send_resolved: true
        # channel: '#petclinic-alerts'
        channel:  ${SLACK_CHANNEL}
        username: ${SLACK_USERNAME}
        title: '[Petclinic {{ .Status | toUpper }}] {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }}'
        text: |
          *Severity:* {{ .CommonLabels.severity | default "info" }}
          *Summary:*  {{ .CommonAnnotations.summary }}
          *Details:*  {{ .CommonAnnotations.description }}

    # Uncomment to use email instead of Slack
    # email_configs:
    #   - to: '${ALERT_TO_EMAIL}'
    #     from: '${ALERT_FROM_EMAIL}'
    #     smarthost: 'smtp.example.com:587'
    #     auth_username: '${ALERT_FROM_EMAIL}'
    #     auth_password: '${SMTP_PASSWORD}'
